/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControlGym;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import modelo.RegistroPersona;

/**
 *
 * @author usuario
 */
public class GUIVentana extends javax.swing.JFrame {

    /**
     * Creates new form GUIVentana
     */
    private RegistroPersona registroPer;

    public GUIVentana() {
        initComponents();
        registroPer = new RegistroPersona();
        ControlGym controlG = new ControlGym(registroPer);
        escucharBarra(controlG);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mi_salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mi_registro = new javax.swing.JMenuItem();
        mi_pagos = new javax.swing.JMenuItem();
        mi_reporte = new javax.swing.JMenuItem();
        mi_atrasos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Ayuda");

        mi_salir.setText("Salir");
        jMenu1.add(mi_salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Archivo");

        mi_registro.setText("Registro");
        jMenu2.add(mi_registro);

        mi_pagos.setText("Pagos");
        jMenu2.add(mi_pagos);

        mi_reporte.setText("Reporte");
        jMenu2.add(mi_reporte);

        mi_atrasos.setText("Atrasos");
        jMenu2.add(mi_atrasos);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mi_atrasos;
    private javax.swing.JMenuItem mi_pagos;
    private javax.swing.JMenuItem mi_registro;
    private javax.swing.JMenuItem mi_reporte;
    private javax.swing.JMenuItem mi_salir;
    // End of variables declaration//GEN-END:variables

    public void escucharBarra(ActionListener control) {
        mi_atrasos.addActionListener(control);
        mi_pagos.addActionListener(control);
        mi_registro.addActionListener(control);
        mi_reporte.addActionListener(control);
        mi_salir.addActionListener(control);
    }

    public static final String MI_REGISTRO="Registro";
    public static final String MI_PAGOS="Pagos";
    public static final String MI_REPORTES="Reporte";
    public static final String MI_ATRASOS="Atrasos";
    public static final String MI_SALIR="Salir";
            
    public static void mensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(null,mensaje);
    }
    

}
